### ISSUE TITLE
can you provide some test dataset？

### ISSUE THREAD

**Issue by taopanpan** [stepanmracek/icrc#1]

**Comment by stepanmracek** [comment]
Hi,
I have plenty of videos, however, I do not have permission to share them.

If you want, you can download videos containing echo-cardiograms from rats here: https://www.dropbox.com/sh/pw3bcn7cg3fwnog/AACmq9iRZgdXAXZ4xe0IcfXAa?dl=0

**Comment by taopanpan** [comment]
Sorry again to bother you again, the program debugging is successful, but I do not know how to run, i also downloaded the data, but i do not know what the model refers to, can  you explain  what is the model's xml ?
